m1 = input(" enter the marks of student 1 : ")
m1 = int(m1)
m2 = input(" enter the marks of student 2 : ")
m2 = int(m2)
m3 = input(" enter the marks of student 3 : ")
m3 = int(m3)
m4 = input(" enter the marks of student 4 : ")
m4 = int(m4)
m5 = input(" enter the marks of student 5 : ")
m5 = int(m5)
m6 = input(" enter the marks of student 6 : ")
m6 = int(m6)
m = [m1,m2,m3,m4,m5,m6]
print(m)
m.sort()
print(m)