num1= int(input("enter number 1 : "))
num2= int(input("enter number 2 : "))
num3= int(input("enter number 3 : "))
num4= int(input("enter number 4 : "))
num5= int(input("enter number 5 : "))
num6= int(input("enter number 6 : "))
num7= int(input("enter number 7 : "))
num8= int(input("enter number 8 : "))
num9= int(input("enter number 9 : "))
num10= int(input("enter number 10 : "))
s = {num1, num2, num3, num4, num5, num6, num7, num8, num9, num10}
print(s)
